ERROR log_conf.py 2019-08-20 17:20:00,871 49 HTTPConnectionPool(host='v.juhe.cn', port=80): Max retries exceeded with url: /weather/index?key=b4a415d875b91358b4f46ca3c1c08bea&cityname=%E6%AD%A6%E6%B1%89 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000000000349B9E8>, 'Connection to v.juhe.cn timed out. (connect timeout=0.001)'))
ERROR log_conf.py 2019-08-20 17:20:00,875 49 HTTPConnectionPool(host='v.juhe.cn', port=80): Max retries exceeded with url: /weather/index (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000000034B9278>, 'Connection to v.juhe.cn timed out. (connect timeout=0.001)'))
ERROR log_conf.py 2019-08-20 17:23:14,497 49 HTTPConnectionPool(host='v.juhe.cn', port=80): Max retries exceeded with url: /weather/index?key=b4a415d875b91358b4f46ca3c1c08bea&cityname=%E6%AD%A6%E6%B1%89 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000000034AB9B0>, 'Connection to v.juhe.cn timed out. (connect timeout=0.01)'))
ERROR log_conf.py 2019-08-20 17:23:14,515 49 HTTPConnectionPool(host='v.juhe.cn', port=80): Max retries exceeded with url: /weather/index (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000000034DE940>, 'Connection to v.juhe.cn timed out. (connect timeout=0.01)'))
ERROR log_conf.py 2019-08-20 17:24:48,475 49 HTTPConnectionPool(host='v.juhe.cn', port=80): Max retries exceeded with url: /weather/index?cityname=%E6%AD%A6%E6%B1%89&key=b4a415d875b91358b4f46ca3c1c08bea (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000000034AC978>, 'Connection to v.juhe.cn timed out. (connect timeout=0.01)'))
ERROR log_conf.py 2019-08-20 17:31:44,230 49 HTTPConnectionPool(host='v.juhe.cn', port=80): Max retries exceeded with url: /weather/index?cityname=%E6%AD%A6%E6%B1%89&key=b4a415d875b91358b4f46ca3c1c08bea (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000000034CC9B0>, 'Connection to v.juhe.cn timed out. (connect timeout=0.01)'))
